### ISSUE TITLE
List of Current World Presidents scraper

### ISSUE THREAD

**Issue by joeyinbox** [opensanctions/opensanctions.org#10]
Hi, 

Unfortunately, _EveryPolitician_ list does not feature the current world leaders.
To complete it, I wrote a scraper based on the following list:
http://www.worldpresidentsdb.com/list/current/

You can find the scraper code under my GitHub account:
https://github.com/joeyinbox/worldpresidentsdb

Here is the scraper working on morph.io:
https://morph.io/joeyinbox/worldpresidentsdb

I would be more than happy if you could consider adding it to the other OpenSanctions sources.

Best regards,
Joey

**Comment by pudo** [comment]
Thanks for writing this scraper. It's now on the web site!
